# Generated by Django 5.0.6 on 2024-08-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_img',
            name='category',
            field=models.CharField(default='nature', max_length=30),
        ),
    ]
